/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-09-12 05:24:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class viewModel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\"\n");
      out.write("\"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\" />\n");
      out.write("<meta name=\"description\" content=\"_your description goes here_\" />\n");
      out.write("<meta name=\"keywords\" content=\"_your,keywords,goes,here_\" />\n");
      out.write("<meta name=\"author\" content=\"_your name goes here_  / Original design: Andreas Viklund - http://andreasviklund.com/\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"andreas05.css\" />\n");
      out.write("<title>Sara And John</title>\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.6.1.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("//Change to Your API Key!!\n");
      out.write("var apikey = \"e5WP8Ur2OIBGu6J2SXYna0r2aGw=\";\n");
      out.write("\n");
      out.write("function doJob(){\n");
      out.write("\t\n");
      out.write("\tvar mcode = $(\"#mcode\").val();\n");
      out.write("\t\n");
      out.write("\t//alert(mcode);\n");
      out.write("\t$(\"#mcodeSpan\").html(\"No Result<br/>\");\n");
      out.write("\t$(\"#mdesc\").html(\"\");\n");
      out.write("\t\n");
      out.write("\tif(mcode != 'ALL'){\n");
      out.write("\t\tvar url = \"http://tFactory.com:8000/tFactory/model/open/json/\"+mcode+\"?key=\"+encodeURIComponent(apikey);\n");
      out.write("\t \t$.getJSON(url, function(data){\n");
      out.write("\t\t\t//alert(data.modelVO.mcode);\n");
      out.write("\t\t\t$(\"#mcodeSpan\").html(\"- Model Code : \" + data.modelVO.mcode+\"<br/>- Model Name : \"+data.modelVO.mname);\n");
      out.write("\t\t\t$(\"#mdesc\").html(data.modelVO.mdesc);\n");
      out.write("\t\t}); \n");
      out.write("\t}else {\n");
      out.write("\t\t\n");
      out.write("\t\talert(\"get All models data\");\n");
      out.write("\t\t\n");
      out.write("\t \t$.getJSON(\"http://tFactory.com:8000/tFactory/model/open/json/all?key\"+encodeURIComponent(apikey),function(response){\n");
      out.write("\t \t\t\n");
      out.write("\t \t\t\n");
      out.write("\t\t\t$.each(response.list,function(i, data){ \n");
      out.write("\t\t\t\t$(\"#mcodeSpan\").append(\"- \" + data.mcode+\"<br>\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t);//end each\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\t);\n");
      out.write("\t\t\n");
      out.write("\t}\t\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<div id=\"title\"><h1>John connor's Site</h1></div>\n");
      out.write("<div id=\"container\">\n");
      out.write("<div id=\"sidebar\">\n");
      out.write("\n");
      out.write("<h2>Site menu</h2>\n");
      out.write("<a class=\"menu\" href=\"main.do\">Main page</a>\n");
      out.write("<a class=\"menu\" href=\"viewModel.do\">Connect TFactory</a>\n");
      out.write("<a class=\"menu\" href=\"viewPosition.do\">Connect Satellite</a>\n");
      out.write("<a class=\"menu\" href=\"#\">Sample</a>\n");
      out.write("<a class=\"menu\" href=\"#\">Sample</a>\n");
      out.write("<a class=\"menu\" href=\"#\">Sample</a>\n");
      out.write("<a class=\"menu\" href=\"#\">Sample</a>\n");
      out.write("<a class=\"menu\" href=\"#\">Sample</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div id=\"main\">\n");
      out.write("<h2>andreas05 - the simple solution!</h2>\n");
      out.write("<img src=\"dragonmini.png\" width=\"125\" height=\"125\" alt=\"Dragon screenshot\" />\n");
      out.write("<p>Model Code : <input type=\"text\" id=\"mcode\" value=\"T1000\"></input><a href=\"javascript:doJob();\">VIEW</a></p>\n");
      out.write("<p><strong><span id=\"mcodeSpan\"></span></strong>\n");
      out.write("   <div id=\"mdesc\">\n");
      out.write("   </div>\n");
      out.write("</p>\n");
      out.write("\n");
      out.write("<h2>An open source design!</h2>\n");
      out.write("<p>This design is released as open source, which means that you can make any changes you may want to, and use the page in any way you want to. Have fun! If you want more designs to choose from, you can visit <a href=\"http://oswd.org/userinfo.phtml?user=Andreas\">my page</a> at OSWD.org, or download my other designs directly: <a href=\"http://www.oswd.org/download.phtml/andreas01.zip?id=2199\">01</a> |\n");
      out.write("<a href=\"http://www.oswd.org/download.phtml/andreas02.zip?id=2204\">02</a> |\n");
      out.write("<a href=\"http://www.oswd.org/download.phtml/andreas03.zip?id=2340\">03</a> |\n");
      out.write("<a href=\"http://www.oswd.org/download.phtml/andreas04.zip?id=2346\">04</a></p>\n");
      out.write("\n");
      out.write("<p class=\"credits\">&copy; 2005 Your name | Design by <a href=\"http://andreasviklund.com\">Andreas Viklund</a></p>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div id=\"footer\"></div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
