/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2017-06-20 07:39:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.tfactory.model.*;
import java.util.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	
	List<ModelVO> list = (List<ModelVO>)request.getAttribute("list");


      out.write("    \n");
      out.write("    \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\"\n");
      out.write("\"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\"/>\n");
      out.write("<meta name=\"description\" content=\"description\"/>\n");
      out.write("<meta name=\"keywords\" content=\"keywords\"/> \n");
      out.write("<meta name=\"author\" content=\"author\"/> \n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../default.css\"/>\n");
      out.write("<title>Blackbox</title>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("function show(mcode){\n");
      out.write("\t\n");
      out.write("\tself.location=\"view/\"+mcode+\".do\";\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("function showJson(mcode){\n");
      out.write("\t\n");
      out.write("\tself.location=\"open/json/\"+mcode;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("function showXml(mcode){\n");
      out.write("\t\n");
      out.write("\tself.location=\"open/xml/\"+mcode;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"main\">\n");
      out.write("\t<div class=\"gfx\"><h1>Terminator Factory</h1></div>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/menu.jsp", out, false);
      out.write("\n");
      out.write("\t\n");
      out.write("\t<div class=\"content\">\n");
      out.write("\t\n");
      out.write("\t ");
 for(ModelVO vo:list) {
      out.write("\n");
      out.write("\t\n");
      out.write("\t\t<div class=\"item\" onclick=\"javascript:show('");
      out.print(vo.getMcode());
      out.write("')\">\n");
      out.write("\t\t  \n");
      out.write("\t\t  <h1 style=\"font-size: 1.5em\"><a href=\"javascript:showJson('");
      out.print(vo.getMcode());
      out.write("')\">JSON</a>  <a href=\"javascript:showXml('");
      out.print(vo.getMcode());
      out.write("')\">XML</a></h1>\n");
      out.write("\t\t  \n");
      out.write("\t\t  \n");
      out.write("\t\t  <ul>\n");
      out.write("\t\t\t<li class='tcode'>");
      out.print(vo.getMcode() );
      out.write("</li> \n");
      out.write("\t\t\t<li>");
      out.print(vo.getMname() );
      out.write("</li>\n");
      out.write("\t\t\t<li>");
      out.print(vo.getMdesc() );
      out.write("</li>\n");
      out.write("\t\t\t\n");
      out.write("\t      </ul>\n");
      out.write("\t      ");
 if(vo.getMimg() != null) { 
      out.write("\n");
      out.write("\t      <img src='../upload/");
      out.print(vo.getMimg() );
      out.write("' width=\"200\" height=\"200\"/>\n");
      out.write("\t      ");
 } 
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t");
  } 
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"footer\">&copy; 2006 <a href=\"index.html\">Sitename.com</a>. Design by <a href=\"http://arcsin.se\">Arcsin</a></div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
